/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const IconMdiAccount: typeof import('~icons/mdi/account.svelte')['default']
  const IconMdiDashboard: typeof import('~icons/mdi/dashboard.svelte')['default']
  const IconMdiList: typeof import('~icons/mdi/list.svelte')['default']
  const IconMdiProject: typeof import('~icons/mdi/project.svelte')['default']
  const IconMdiSort: typeof import('~icons/mdi/sort.svelte')['default']
  const IconMdiStorage: typeof import('~icons/mdi/storage.svelte')['default']
  const IconMdiTestimonial: typeof import('~icons/mdi/testimonial.svelte')['default']
  const IconMdiUpload: typeof import('~icons/mdi/upload.svelte')['default']
}
